Fixed errors and finished frequencyFile function.
Error: printCodes not printing the Huffman Codes in terminal.
    The problem stems from MinHeap as when we initialize each array[i] with a nullptr. When insert it with a lot of null pointers into MinHeap min.insert(nullptr) will cause shiftUp() and sink() to dereference a nullptr

Finished implementing for reading a file, and parsing character frequencies and storing them to Node* array.